@startuml
skinparam backgroundcolor monochrome
'skinparam monochrome true
skinparam defaultTextAlignment center
skinparam titleFontSize 22
skinparam handwritten true

!define SPRITESURL https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites
!includeurl SPRITESURL/user.puml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0
!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome-5/cc_stripe.puml

skinparam rectangle {
  borderColor Black
  backgroundColor #fff
}
skinparam agent {
  borderColor Black
  backgroundColor #fff
}
skinparam sequence{
  arrowColor Black
}
skinparam usecase {
  borderColor #fff
  backgroundColor #fff
  shadowing false
  fontSize 18
}

title

Threat Model | Attack Tree | Payment Online

end title

'legend left
'text
'endlegend

footer

end footer

(key entities/actors within \nthe payment process) as subtitle

rectangle "<$user>\nThreat" as threat #Thistle
rectangle "<$user>\nCustomer" as customer #LightGoldenRodYellow
rectangle "<$user>\nMerchant" as merchant #LightGoldenRodYellow
FA5_CC_STRIPE(stripe,Stripe) #LightGoldenRodYellow

'threat  <. subtitle
'subtitle .> stripe
'subtitle .> merchant
'subtitle .> customer
subtitle .> threat
stripe <. subtitle
merchant <. subtitle
customer <. subtitle

' Root nodes
agent "Intent - Disrupt Merchant Business" as goalDisrupt
agent "Intent - Steal Credit Card Details" as goalSteal

subtitle ... goalDisrupt #fff
subtitle ... goalSteal #fff

' goalDisrupt
agent "Prevent Purchases \nor Subscriptions" as goalPrevent
agent "Use fraudulent \ncredit card" as goalFraudulentCC
agent "Take advantage of Misconfiguration \n& vulnerabilities" as goalApp
agent "Target Stripe API" as goalStripeApi
agent "Compromise and \nor steal employee laptop \nand mobile phone" as goalLaptop
agent "Create a \nMock website" as goalMock
agent "Domain Hijacking" as goalDomain

goalDisrupt --> goalPrevent
goalDisrupt --> goalFraudulentCC
goalDisrupt --> goalApp
goalDisrupt --> goalStripeApi
goalDisrupt --> goalLaptop
goalDisrupt --> goalMock
goalDisrupt --> goalDomain

note top of goalFraudulentCC #LightGoldenRodYellow: Thwarted by implementing 3D Secure

agent "Hoax Purchases" as goalHoax
agent "Target Merchant API" as goalMerchantApi

goalPrevent --> goalHoax
goalPrevent --> goalMerchantApi

agent "Denial of Service" as goalDoS

goalMerchantApi --> goalDoS

agent "Compromise Merchant servers" as goalServers

goalApp --> goalServers

agent "Tamper with Application \ncausing outage" as goalCrash
agent "App removed from \nthe App Store" as goalRemoveStore

goalServers --> goalCrash
goalServers --> goalRemoveStore

agent "Gain access to Stripes \nMerchant Dashboard" as goalMerchantDashboard

goalLaptop --> goalMerchantDashboard

agent "Reset Administrative Access" as goalMerchantAccess
agent "Revoke or steal keys \nused in PaymentIntent" as goalMerchantKeys
agent "Issue refunds, \ncancel Subscriptions" as goalRefund
agent "Create or Delete \nCustomers" as goalDeleteUsers

goalMerchantDashboard --> goalMerchantAccess
goalMerchantDashboard --> goalMerchantKeys
goalMerchantDashboard --> goalRefund
goalMerchantDashboard --> goalDeleteUsers

agent "Site no longer \nresponds or displays \ndifferent content" as goalSite

goalDomain --> goalSite

' goalSteal
agent "Target Customer Details \nstored by Merchant (db)" as goalCustLogin
agent "Target Customer Client \n(home pc)" as goalCustClient
agent "Target Stripe" as goalStripe

goalSteal --> goalCustLogin
goalSteal --> goalCustClient
goalSteal --> goalStripe

agent "Target known \nCustomers of Merchant" as goalSocial
agent "Target Stripe for \nadministrative rights" as goalStripeAdmin

goalCustLogin  --> goalSocial
goalCustClient --> goalSocial
goalStripe --> goalStripeAdmin

agent "Lateral movement \nwithin organization" as goalLateral

goalStripeAdmin --> goalLateral

goalMock  --> goalSocial
goalStripeApi --> goalDoS

agent "Social Engineering \nphishing" as goalPhishing
agent "Session hijacking" as goalSessionHijacking

goalSocial --> goalPhishing
goalSocial --> goalSessionHijacking

@enduml